services:
  mailpit:
    image: axllent/mailpit:latest
    container_name: jp3d-mailpit
    restart: unless-stopped
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # Web UI
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: "" # Keep in memory
