import type { Metadata } from "next";
import { routes } from "@/shared/config/routes";

const metadata: Metadata = {
  title: routes.name,
  description: "Generated by create next app",
};

export default metadata;
